
name: Build and deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Run when the main branch is pushed
on:
  push:
    branches:
      - main

# Jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.86.0"
          extended: true

      - name: Build
        run: hugo --minify --environment production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          user_name: 'RowBot'
          user_email: '48598026+rowanbot@users.noreply.github.com'
          publish_dir: ./build
          publish_branch: build
          cname: sample-feeds.rowanmanning.com
